### PR TITLE
1 to many

### PR DESCRIPTION
**Pull request by thisAKcode**
Hey, I am still stuck at 1-M modelling.
I created a new models as per your suggestion> 
I tried to recreate the db (cut out mydb.db sqlite file into /backup) , then I expect that following will bring the new db with new , tables and schemas:
 app/main.py
```
@app.on_event("startup")
async def startup_populate_db():
    db = SessionLocal()
    item_count = db.query(model.Item).count()
    if item_count == 0:
        insert_items(DUMMY_DATA)
```

Then I get : 
```  File "c:\fastapi_streetart_map\venv\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: item._data
```

Weird since I not only miss _data column, the entire db is not there...

### CODE REVIEW

**Comment by thisAKcode** [comment]
> Hey, I am still stuck at 1-M modelling. I created a new models as per your suggestion> I tried to recreate the db (cut out mydb.db sqlite file into /backup) , then I expect that following will bring the new db with new , tables and schemas: app/main.py
> 
> ```
> @app.on_event("startup")
> async def startup_populate_db():
>     db = SessionLocal()
>     item_count = db.query(model.Item).count()
>     if item_count == 0:
>         insert_items(DUMMY_DATA)
> ```
> 
> Then I get :
> 
> ```
>     cursor.execute(statement, parameters)
> sqlite3.OperationalError: no such column: item._data
> ```
> 
> Weird since I not only miss _data column, the entire db is not there...

I reviewed that myself is that because of my Schemas.py are not the sames as model.py? In this case you do not need to review in detail I'll just work on it further.

**Comment by bbelderbos** [comment]
OK let me know what fixed it ...

Now I remember you had to define pydantic and sqlalchemy models which causes some duplicated code, SQLModel solves this :)

**Comment by thisAKcode** [comment]
Well, it was silly mistake : I removed mydb.db from root but it existed also in /app/ wich application tried to insert into, of course error 'missing column blabla' was appropriate error then.
I couldn't make pr tonight. Maybe tomorrow otherwise it can wait untill next week.
Alex

Hämta Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bbelderbos** [comment]
oh sneaky so two databases and it accessed the wrong one?

**Comment by thisAKcode** [comment]
No both were with old data schema, goal was to remove db and create it from scratch, wich i thought was done. Sorry I was sick this week so I couldn't code so much but I have todos so I ll try to code it soon , hopefully during weekend

Hämta Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bbelderbos** [comment]
Yeah common issue, when you have real data in production, you need to use alembic though. Feel better!

**Pull request merged**
